### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by drmzio** [OvercastCommunity/overcastcommunity.github.io#36]
Users will see broken Twitch embeds whilst browsing on a non-secured network. Tested in latest Chrome. http://oc.tc/live/

## Screenshot

![](https://p193.p3.n0.cdn.getcloudapp.com/items/4guO5B52/Image%202020-11-30%20at%202.35.19%20PM.jpg?v=9683a746967e1cb15d7182621284f86c)

## How to fix

Enable **Enforce HTTPS** on the GitHub page settings. [See docs](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site)

**Comment by Brottweiler** [comment]
The issue is not the twitch page, it is that HTTPS is not enforced. 

The website is behind Cloudflare. The Enforce HTTPS option is greyed out for me via GitHub. It has to be handled via Cloudflare and I am not the one in control of our Cloudflare.

Thank you for reporting this and I'll try to get this solved.

**Comment by unixfox** [comment]
No need to control Cloudflare, you can enforce HTTPS in the settings of this repisitory: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

**Comment by Brottweiler** [comment]
> No need to control Cloudflare, you can enforce HTTPS in the settings of this GitHub repository

No.
